// FILE: config.js

const SHORTENERS = {
    'bit.ly': 'Bitly',
    'tinyurl.com': 'TinyURL',
    'ow.ly': 'Hootsuite',
    'is.gd': 'is.gd',
    'buff.ly': 'Buffer',
    'rebrand.ly': 'Rebrandly',
    'short.link': 'Short.link',
    'goo.gl': 'Google (deprecated)',
    't.co': 'Twitter/X',
    'lnkd.in': 'LinkedIn',
    'rb.gy': 'Rebrandly',
    'v.gd': 'v.gd',
    'cutt.ly': 'Cutt.ly',
    'urlzs.com': 'URLZS',
    'shorte.st': 'Shorte.st',
    'adf.ly': 'AdFly',
    'bc.vc': 'BC.VC'
};

const BYPASS_SERVICES = {
    ad_shorteners: {
        'linkvertise.com': 'Linkvertise',
        'linkvertise.download': 'Linkvertise',
        'link-center.net': 'Linkvertise',
        'link-target.net': 'Linkvertise',
        'link-hub.net': 'Linkvertise',
        'link-to.net': 'Linkvertise',
        'direct-link.net': 'Linkvertise',
        'file-link.net': 'Linkvertise',
        'cuty.io': 'Cutty',
        'cuttty.com': 'Cutty',
        'shrinkme.click': 'ShrinkMe',
        'sub2get.com': 'Sub2Get',
        'sub2unlock.me': 'Sub2Unlock',
        'sub2unlock.com': 'Sub2Unlock',
        'sub2unlock.net': 'Sub2Unlock',
        'loot-links.com': 'Lootlinks',
        'loot-link.com': 'Lootlinks',
        'lootlinks.co': 'Lootlinks',
        'lootlink.org': 'Lootlinks',
        'lootdest.org': 'Lootlinks',
        'linksloot.net': 'Lootlinks',
        'links-loot.com': 'Lootlinks',
        'lootdest.com': 'Lootlinks',
        'links.lootlabs.gg': 'Lootlinks',
        'adfoc.us': 'AdFoc.us',
        'boost.ink': 'Boost.ink',
        'bst.gg': 'Boost.ink',
        'bst.wtf': 'Boost.ink',
        'booo.st': 'Boost.ink',
        'boost.fusedgt.com': 'BoostFusedGT',
        'letsboost.net': 'LetsBoost',
        'mboost.me': 'mboost.me',
        'rekonise.com': 'Rekonise',
        'rkns.link': 'Rekonise',
        'sh.st': 'Shorte.st',
        'gestyy.com': 'Shorte.st',
        'destyy.com': 'Shorte.st',
        'egirls.wtf': 'egirls.wtf',
        'leasurepartment.xyz': 'leasurepartment.xyz',
        'gplinks.co': 'GPLinks',
        'just2earn.com': 'Just2Earn',
        'exe.io': 'Exe.io'
    },
    paste_services: {
        'pastebin.com': 'Pastebin',
        'pastelua.com': 'PasteLua',
        'pastelink.net': 'Pastelink',
        'pastesite.net': 'Pastesite',
        'rentry.org': 'Rentry',
        'rentry.co': 'Rentry',
        'jpst.it': 'JustpasteIt',
        'gopaste.link': 'EcoDevs',
        'getpaste.link': 'EcoDevs',
        'notecanyon.com': 'EcoDevs',
        'pastehill.com': 'EcoDevs',
        'spacebin.in': 'EcoDevs',
        'pastecanyon.com': 'EcoDevs',
        'freepaste.link': 'EcoDevs',
        'justetext.com': 'EcoDevs',
        'pastetoday.com': 'EcoDevs',
        'pastemega.com': 'EcoDevs',
        'expaste.com': 'EcoDevs',
        'pastemake.online': 'EcoDevs',
        'pastezone.site': 'EcoDevs',
        'pastemode.com': 'EcoDevs',
        'paskyk.com': 'EcoDevs',
        'mypastelink.com': 'EcoDevs',
        'controlc.com': 'ControlC',
        'paste.work.ink': 'PasteWorkInk',
        'paste.to': 'PrivateBin',
        'paster.so': 'PasterSo',
        'hastebin.skyra.pw': 'Hastebin',
        'hastebin.de': 'Hastebin',
        'paste-drop.com': 'PasteDrop',
        'leakutopia.click': 'Leakutopia',
        'leakslinks.com': 'LeaksLinks',
        'goldpaster.pro': 'Goldpaster',
        'pasteso.com': 'Pasteso',
        'link-direct.xyz': 'LinkDirect',
        'link-direct.pro': 'LinkDirect',
        'n0paste.eu': 'n0paste',
        'pasteflash.com': 'PasteFlash',
        'pasteva.com': 'Pasteva',
        'leaked.tools': 'Leaked.tools',
        'telegra.ph': 'Telegraph',
        'vaultlinks.xyz': 'Vaultlinks'
    },
    special_resolvers: {
        'bestnsfw.site': 'RedirectResolver',
        'directlinker.com': 'RedirectResolver',
        'pasterlink.com': 'RedirectResolver',
        'up-to-down.net': 'RedirectResolver',
        'subfinal.com': 'SubFinal',
        'subtolink.com': 'SubFinal',
        'justpaster.lol': 'LocationRedirect'
    }
};

const PASTE_SELECTORS = {
    'pastebin.com': '.de1, .de2, .text',
    'rentry.co': '.rentry-content',
    'rentry.org': '.rentry-content',
    'justpaste.it': '.post-content',
    'pastelink.net': '.paste-content',
    'controlc.com': '#code'
};

const BYPASS_BUTTONS = [
    '#btn', '.verify', '.timerBtn', '.continue-btn', '.skip-btn', '.go-btn',
    '.submit-btn', '.next-btn', '.click-btn',
    'button[onclick*="verify"]', 'button[onclick*="continue"]',
    'button[onclick*="skip"]', 'button[onclick*="go"]',
    'a[onclick*="verify"]', 'a[onclick*="continue"]',
    '.btn-continue', '.btn-verify', '.btn-skip',
    '#continue-button', '#verify-button', '#skip-button'
];

const BYPASS_PATTERNS = [
    /location\.href\s*=\s*["']([^"']+)["']/i,
    /window\.location\s*=\s*["']([^"']+)["']/i,
    /window\.location\.href\s*=\s*["']([^"']+)["']/i,
    /top\.location\.href\s*=\s*["']([^"']+)["']/i,
    /parent\.location\.href\s*=\s*["']([^"']+)["']/i,
    /self\.location\s*=\s*["']([^"']+)["']/i,
    /document\.location\s*=\s*["']([^"']+)["']/i,
    /window\.open\s*\(\s*["']([^"']+)["']/i,
    /setTimeout\s*\(\s*function\s*\(\)\s*\{\s*window\.location\s*=\s*["']([^"']+)["']/i,
    /<meta[^>]*http-equiv=["']refresh["'][^>]*content=["']\d+;\s*url=(.+?)["']/i,
    /<a[^>]*href=["']([^"']+)["'][^>]*>(?:Continue|Verify|Skip|Next|Click)[^<]*<\/a>/i,
    /<iframe[^>]*src=["']([^"']+)["']/i,
    /var\s+url\s*=\s*["']([^"']+)["']/i,
    /let\s+url\s*=\s*["']([^"']+)["']/i,
    /const\s+url\s*=\s*["']([^"']+)["']/i,
    /redirectUrl\s*=\s*["']([^"']+)["']/i,
    /destinationUrl\s*=\s*["']([^"']+)["']/i,
    /finalUrl\s*=\s*["']([^"']+)["']/i,
    /goToUrl\s*=\s*["']([^"']+)["']/i,
    /nextUrl\s*=\s*["']([^"']+)["']/i,
    /continueUrl\s*=\s*["']([^"']+)["']/i,
    /getUrl\s*=\s*["']([^"']+)["']/i
];

const USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

module.exports = {
    SHORTENERS,
    BYPASS_SERVICES,
    PASTE_SELECTORS,
    BYPASS_BUTTONS,
    BYPASS_PATTERNS,
    USER_AGENT
};